export type SessionState =
  | "idle"
  | "preparing"
  | "recording"
  | "paused"
  | "stopping"
  | "completed"
  | "error";

export type PermissionState =
  | "notDetermined"
  | "authorized"
  | "denied"
  | "restricted"
  | "unknown";

export interface PermissionBundle {
  screenRecording: PermissionState;
  camera: PermissionState;
  microphone: PermissionState;
}

export type CaptureSourceType = "display" | "window" | "application";

export interface CaptureSource {
  id: string;
  name: string;
  sourceType: CaptureSourceType;
  width: number;
  height: number;
  thumbnailUrl?: string;
}

export interface AudioDevice {
  id: string;
  name: string;
  isDefault: boolean;
}

export interface CameraDevice {
  id: string;
  name: string;
  isDefault: boolean;
}

export type TrackType = "screen" | "webcam" | "mic" | "system";

export interface TimelineInterval {
  id: string;
  startUs: number;
  endUs: number;
  excluded: boolean;
}

export interface WaveformBucket {
  startUs: number;
  endUs: number;
  peak: number;
  rms: number;
  gap: boolean;
}

export interface WaveformPage {
  trackId: string;
  startUs: number;
  endUs: number;
  sampleRate: number;
  channels: number;
  channelPolicy: string;
  buckets: WaveformBucket[];
  diagnostics: string[];
  cancelled: boolean;
}

export interface Track {
  id: string;
  trackType: TrackType;
  name: string;
  muted: boolean;
  volume: number; // 0.0 to 1.0
  intervals: TimelineInterval[];
  waveform?: WaveformPage;
}

export interface ZoomKeyframe {
  id: string;
  tUs: number;
  normX: number; // 0.0 to 1.0
  normY: number; // 0.0 to 1.0
  scale: number; // e.g. 1.5, 2.0
  durationMs: number;
  isAutoGenerated?: boolean;
}

export type CameraBubbleShape = "circle" | "squircle" | "rect_16_9";
export type CameraBubbleSize = "sm" | "md" | "lg" | "xl";
export type CameraBubblePosition = "top-left" | "top-right" | "bottom-left" | "bottom-right" | "custom";

export interface CameraBubbleSettings {
  enabled: boolean;
  shape: CameraBubbleShape;
  size: CameraBubbleSize;
  position: CameraBubblePosition;
  customX: number;
  customY: number;
  borderColor: string;
  borderWidth: number;
  mirror: boolean;
  shadow: boolean;
}

export interface CanvasSettings {
  backgroundType: "gradient" | "solid" | "wallpaper";
  colorStart: string;
  colorEnd: string;
  paddingPx: number; // 0 to 80
  cornerRadiusPx: number; // 0 to 32
  shadowBlurPx: number; // 0 to 40
  shadowOpacity: number; // 0.0 to 1.0
  aspectRatio: "16:9" | "9:16" | "4:3" | "1:1";
}

export interface SilenceConfig {
  thresholdDb: number; // e.g. -38
  minDurationMs: number; // e.g. 400
  paddingMs: number; // e.g. 50
}

export interface SilenceBlock {
  id: string;
  startUs: number;
  endUs: number;
  durationMs: number;
  selected: boolean;
}

export type NativeTrackType = "screen" | "webcam" | "mic_audio" | "system_audio";

export interface NativeTrackDescriptor {
  id: string;
  trackType: NativeTrackType;
  codec: string;
  relativePath: string;
  width?: number;
  height?: number;
  fps?: number;
  sampleRate?: number;
  channels?: number;
  gapsTotal: number;
  mediaTimescale?: number;
}

export interface ProjectManifest {
  version: number;
  sessionId: string;
  projectName: string;
  createdAt: string;
  durationUs: number;
  activeDurationUs: number;
  gapsTotal: number;
  pauseIntervals: { startUs: number; endUs: number }[];
  cursorMode?: string;
  sourceGeometry?: unknown;
  tracks: NativeTrackDescriptor[];
}

export interface TrackSummary {
  descriptor: NativeTrackDescriptor;
  segmentCount: number;
  availableSegmentCount: number;
}

export interface RetainedInterval {
  startUs: number;
  endUs: number;
}

export interface OpenedProject {
  projectHandle: string;
  revision: number;
  manifest: ProjectManifest;
  sourceDurationUs: number;
  editedDurationUs: number;
  retainedIntervals: RetainedInterval[];
  tracks: TrackSummary[];
  diagnostics: string[];
  previewAvailable: boolean;
  undoAvailable: boolean;
  redoAvailable: boolean;
}

export type PlaybackState =
  | "closed"
  | "ready"
  | "playing"
  | "paused"
  | "seeking"
  | "ended"
  | "error";

export type ClockKind = "audio" | "monotonic";

export interface TrackDecodePlan {
  trackId: string;
  generation: number;
  editedUs: number;
  sourceUs: number | null;
  gap: boolean;
  ended: boolean;
  relativePath: string | null;
  keyframeSourceUs: number | null;
  decodeToSourceUs: number | null;
}

export interface PlaybackStatus {
  projectHandle: string;
  state: PlaybackState;
  generation: number;
  positionUs: number;
  durationUs: number;
  clockKind: ClockKind;
  previewAvailable: boolean;
  openFiles: number;
  plans: TrackDecodePlan[];
  error: string | null;
  diagnostics: string[];
}

export interface EditCut {
  startUs: number;
  endUs: number;
}

export type PreviewHitMode = "consume" | "circle";

export interface PreviewViewport {
  generation: number;
  clip?: [number, number, number, number];
  windowLabel: string;
  x: number;
  y: number;
  width: number;
  height: number;
  backingScale: number;
  visible: boolean;
  occluded: boolean;
  revision: number;
}

export interface PreviewStatus {
  attached: boolean;
  windowLabel: string | null;
  generation: number;
  layoutRevision: number;
  arrangement: string;
  supported: boolean;
  presentedKind: string;
  copiesPerPresent: number;
  copies: number;
  presentedBytes: number;
  backingScale: number;
  physical: { x: number; y: number; width: number; height: number } | null;
  visible: boolean;
  occluded: boolean;
  hitMode: PreviewHitMode;
  diagnostics: string[];
}

export interface MediaInteropStatus {
  decoderBackend: string;
  compositorBackend: string;
  encoderBackend: string;
  ffmpegPinned: boolean;
  supported: boolean;
  previewAvailable: boolean;
  copiesDecode: number;
  copiesComposite: number;
  copiesEncode: number;
  concurrentEncoderLimit: number;
  colorSpace: string;
  wgpuAdapter: string | null;
  diagnostics: string[];
}

export interface MediaParityReport {
  matched: boolean;
  previewWidth: number;
  previewHeight: number;
  exportWidth: number;
  exportHeight: number;
  previewPtsUs: number;
  exportPtsUs: number;
  maxAbsDelta: number;
  meanAbsDelta: number;
  regionMeanDelta: number;
  compositorMeanDelta: number;
  compositorMaxDelta: number;
  copiesDecode: number;
  copiesComposite: number;
  copiesEncode: number;
  concurrentEncoderLimit: number;
  decoderBackend: string;
  compositorBackend: string;
  encoderBackend: string;
  ffmpegPinned: boolean;
  colorSpace: string;
  pcmPeak: number;
  pcmRms: number;
  diagnostics: string[];
}

export type ExportState =
  | "idle"
  | "queued"
  | "running"
  | "completed"
  | "failed"
  | "cancelled";

export type ExportFailureKind =
  | "collision"
  | "cancelled"
  | "invalid_settings"
  | "source_path"
  | "recording_active"
  | "encoder_busy"
  | "native"
  | "io";

export interface ExportFailure {
  kind: ExportFailureKind;
  message: string;
}

export interface ExportSettings {
  videoCodec: "h264";
  audioCodec: "aac";
  width: number;
  height: number;
  fps: number;
  destination?: string | null;
}

export interface ExportStatus {
  jobId: string;
  state: ExportState;
  capturedRevision: number;
  videoCodec: string;
  audioCodec: string;
  width: number;
  height: number;
  fps: number;
  progressNumerator: number;
  progressDenominator: number;
  outputPath: string | null;
  failure: ExportFailure | null;
  diagnostics: string[];
}

export interface SegmentSummary {
  trackId: string;
  relativePath: string;
  startUs: number;
  endUs: number;
  sizeBytes: number;
  mediaTimescale: number;
  mediaStartValue: number;
  hostAnchorUs: number;
  isKeyframeStart: boolean | null;
  available: boolean;
}

export interface SegmentPage {
  segments: SegmentSummary[];
  nextOffset: number | null;
}

export interface StopRecordingResult {
  projectPath: string;
  sessionId: string;
  state: SessionState;
  durationUs: number;
}

export function studioTrackType(trackType: NativeTrackType): TrackType {
  if (trackType === "mic_audio") return "mic";
  if (trackType === "system_audio") return "system";
  return trackType;
}

export interface TelemetryEvent {
  version: number;
  seq: number;
  tUs: number;
  geometryId: string;
  kind: "move" | "down" | "up" | "click" | "scroll";
  normX: number;
  normY: number;
  insideSource: boolean;
  visible: boolean;
  cursorId?: string;
}
